### ISSUE TITLE
springcloud config refresh

### ISSUE THREAD

**Issue by fanxing-zhao** [seltonGitHub/springclouddemo1#1]
## 配置更新消息总线

[总篇概述](http://ityouknow.com/spring-cloud.html)

启动rabbitmq

在总pom中加入依赖

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```

在config server端和用到config的client端的配置文件中加入

与 spring.cloud 平级
```
  rabbitmq:
    host: 192.168.31.224
    port: 5672
    username: guest
    password: guest
```

发起curl

``` shell
curl -X POST http://localhost:8100/actuator/bus-refresh
```

以启动配置自更新策略

### zuul

依赖到module

``` 
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
</dependency>
```

配置

```
zuul:
  routes:
    provider-api:
      path: /provider/**
      serviceId: spring-cloud-eureka-provider
```
